semgrep:
  image: returntocorp/semgrep
  script: semgrep ci{
    sendResults ? " --gitlab-sast > gl-sast-report.json || true" : ""
  }
  
  rules:
  - if: $CI_MERGE_REQUEST_IID
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

  variables:
    SEMGREP_AGENT_DEBUG: 1
    # Gives Semgrep permission to post inline comments
    GITLAB_TOKEN: $PAT


semgrep:
  image: returntocorp/semgrep
  script: semgrep ci{
    sendResults ? " --gitlab-sast > gl-sast-report.json || true" : ""
  }
  variables:
    
  rules:
  - if: $CI_MERGE_REQUEST_IID
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
