on-pull-requests:
  image: returntocorp/semgrep-agent:v1
  script:
    - semgrep-agent --publish-token $SEMGREP_APP_TOKEN

  rules:
    # Scan changed files in MRs, block on new issues only (existing issues ignored)
    - if: $CI_EXTERNAL_PULL_REQUEST_IID
  
  variables:
    SEMGREP_AGENT_DEBUG: 1
    SEMGREP_PR_ID: $CI_EXTERNAL_PULL_REQUEST_IID
    SEMGREP_REPO_NAME: $CI_PROJECT_NAME
    SEMGREP_REPO_URL: $CI_PROJECT_URL
    SEMGREP_JOB_URL: $CI_JOB_URL
    SEMGREP_COMMIT: $CI_COMMIT_SHA
    SEMGREP_BRANCH: $CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME
